WhereToPlay/Controllers/CourtsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using WhereToPlay.Models;
using WhereToPlay.Models.DB;
using WhereToPlay.Models.ViewModel;

namespace WhereToPlay.Controllers
{
    public class CourtsController : Controller
    {
        private WhereToPlayDb db = new WhereToPlayDb();

        // GET: Courts
        public ActionResult Index(string terenCautat)
        {
            if (Request.IsAuthenticated)
            {
                int loggedUserID = db.Users.Where(u => u.UserName == HttpContext.User.Identity.Name).FirstOrDefault().IDUser;
                var courts = db.Courts.Where(c => c.CreateUserID == loggedUserID).Include(c => c.Address).Include(c => c.Sport).Include(c => c.User);
                if (terenCautat == null)
                {
                    return View(courts.ToList());
                }
                else
                {
                    var courtsFilter = courts.Where(c => c.CourtName.Contains(terenCautat)).ToList();
                    if (courtsFilter.Count == 0)
                    {
                        ModelState.AddModelError(string.Empty, "Ne pare rau, nu am gasit nici un teren!");
                    }
                    return View(courtsFilter);
                }
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult IndexSports(string id, string terenCautat)
        {
            if (Request.IsAuthenticated)
            {
                int loggedUserID = db.Users.Where(u => u.UserName == HttpContext.User.Identity.Name).FirstOrDefault().IDUser;
                var courts = db.Courts.Where(c => c.CreateUserID == loggedUserID).Where(s=>s.Sport.SportName==id).Include(c => c.Address).Include(c => c.Sport).Include(c => c.User);
                if(terenCautat==null)
                {
                    return View(courts.ToList());
                }
                else
                {
                    var courtsFilter = courts.Where(c => c.CourtName.Contains(terenCautat)).ToList();
                    if (courtsFilter.Count == 0)
                    {
                        ModelState.AddModelError(string.Empty, "Ne pare rau, nu am gasit nici un teren!");
                    }
                    return View(courtsFilter);
                }
               
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Rezervari()
        {
            if (Request.IsAuthenticated)
            {
                var courts = db.Reservations.Where(r => r.Court.User.UserName==HttpContext.User.Identity.Name && r.ReservationDate>=DateTime.Now).ToList();
                //.Include(c => c.Address).Include(c => c.Sport).Include(c => c.User)
                return View(courts.ToList());  
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult RezervarileMele()
        {
            if (Request.IsAuthenticated)
            {
                var courts = db.Reservations.Where(r => r.User.UserName == HttpContext.User.Identity.Name && r.ReservationDate >= DateTime.Now).ToList();
                //.Include(c => c.Address).Include(c => c.Sport).Include(c => c.User)
                return View(courts.ToList());
            }

            return RedirectToAction("Index", "Home");
        }


        // GET: Courts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Court court = db.Courts.Where(c => c.IDCourt == id).First();
            if (court == null)
            {
                return HttpNotFound();
            }
            return View(court);
        }

        // GET: Courts/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                if (!Allowed())
                {
                    return RedirectToAction("NotAllowed", "Home");
                }
            }
            else
            {
                return RedirectToAction("NotAllowed", "Home");
            }

            ViewBag.AddressID = new SelectList(db.Addresses, "IDAddress", "AddressStreet");
            ViewBag.SportID = new SelectList(db.Sports, "IDSport", "SportName");
            ViewBag.CreateUserID = new SelectList(db.Users, "IDUser", "UserName");
            return View();
        }

        // POST: Courts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Address,CourtName,Length,Width,PhoneNumber,EmailAddress,SessionPrice, SportID")] Court court, HttpPostedFileBase Content1, HttpPostedFileBase Content2, HttpPostedFileBase Content3)
        //,AddressStreet,AddressNumber,AddressCity,AddressCounty
        {
            if (ModelState.IsValid)
            {

                Court myCourt = new Court();
                myCourt.CourtName = court.CourtName;
                myCourt.Length = court.Length;
                myCourt.Width = court.Width;

                if (court.PhoneNumber != null)
                    if (IsPhoneNumber(court.PhoneNumber))
                    {
                        myCourt.PhoneNumber = court.PhoneNumber;
                    }
                    else
                    {
                        ModelState.AddModelError("PhoneNumber", "Campul Numar telefon trebuie sa respecte formatul unui numar de telefon!");
                        return View("Create", court);
                    }
                myCourt.EmailAddress = court.EmailAddress;
                myCourt.CreateUserID = court.CreateUserID;
                myCourt.SessionPrice = court.SessionPrice;

                if (Content1 != null && Content1.ContentLength > 0)
                {
                    byte[] tempFile = new byte[Content1.ContentLength];
                    Content1.InputStream.Read(tempFile, 0, Content1.ContentLength);
                    myCourt.Content1 = tempFile;
                    myCourt.FileName1 = Content1.FileName;      
                }


                if (Content2 != null && Content2.ContentLength > 0)
                {
                    byte[] tempFile = new byte[Content2.ContentLength];
                    Content2.InputStream.Read(tempFile, 0, Content2.ContentLength);
                    myCourt.Content2 = tempFile;
                    myCourt.FileName2 = Content2.FileName;
                }


                if (Content3 != null && Content3.ContentLength > 0)
                {
                    byte[] tempFile = new byte[Content3.ContentLength];
                    Content3.InputStream.Read(tempFile, 0, Content3.ContentLength);
                    myCourt.Content3 = tempFile;
                    myCourt.FileName3 = Content3.FileName;
                }

                Address myAdd = new Address();
                myAdd.AddressStreet = court.Address.AddressStreet;
                myAdd.AddressNumber = court.Address.AddressNumber;
                myAdd.AddressCity = court.Address.AddressCity;
                myAdd.AddressCounty = court.Address.AddressCounty;
                db.Addresses.Add(myAdd);
                db.SaveChanges();

                myCourt.AddressID = myAdd.IDAddress;
                myCourt.Address = db.Addresses.Where(a => a.IDAddress == myCourt.AddressID).FirstOrDefault();

                myCourt.SportID = court.SportID;
                myCourt.Sport = db.Sports.Where(s => s.IDSport == myCourt.SportID).FirstOrDefault();

                myCourt.CreateUserID = db.Users.Where(u => u.UserName == HttpContext.User.Identity.Name).FirstOrDefault().IDUser;
                myCourt.User = db.Users.Where(u => u.IDUser == myCourt.CreateUserID).FirstOrDefault();
                myCourt.User.UserGroup = db.UserGroups.Where(u => u.IDUserGroup == myCourt.User.UserGroupID).FirstOrDefault();
                myCourt.User.UserPasswordConfirm = myCourt.User.UserPassword;

                if (Content1 != null && Content1.ContentLength > 0)
                {
                    if (Content1.ContentLength > 1048576)
                    {
                        ViewBag.AddressID = new SelectList(db.Addresses, "IDAddress", "AddressStreet");
                        ViewBag.SportID = new SelectList(db.Sports, "IDSport", "SportName");
                        ViewBag.CreateUserID = new SelectList(db.Users, "IDUser", "UserName");
                        ModelState.AddModelError("", "Poza 1 trebuia sa aiba maxim 1MB");
                        return View("Create", court);
                    }
                }

                if (Content2 != null && Content2.ContentLength > 0)
                {
                    if (Content2.ContentLength > 1048576)
                    {
                        ViewBag.AddressID = new SelectList(db.Addresses, "IDAddress", "AddressStreet");
                        ViewBag.SportID = new SelectList(db.Sports, "IDSport", "SportName");
                        ViewBag.CreateUserID = new SelectList(db.Users, "IDUser", "UserName");
                        ModelState.AddModelError("", "Poza 2 trebuia sa aiba maxim 1MB");
                        return View("Create", court);
                    }
                }

                if (Content3 != null && Content3.ContentLength > 0)
                {
                    if (Content3.ContentLength > 1048576)
                    {
                        ViewBag.AddressID = new SelectList(db.Addresses, "IDAddress", "AddressStreet");

WhereToPlay/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WhereToPlay.Models;

namespace WhereToPlay.Controllers
{
    public class HomeController : Controller
    {
        private WhereToPlayDb db = new WhereToPlayDb();
        // GET: Home
        public ActionResult Index()
        {
           // Utilities.SmsSend("0764199999", "test din utilities");
           // Utilities.EmailSend("oidldb@gmail.com", "test din utilities", "test din utilities body");
            return View(db.Courts.Where(e=>e.Hidden==false).ToList());
        }

        public ActionResult IndexSports(string id, string terenCautat)
        {
            if (terenCautat == null)
            {
                return View(db.Courts.Where(e => e.Hidden == false).Where(s => s.Sport.SportName == id).ToList());
            }
            else
            {
                var courts = db.Courts.Where(e => e.Hidden == false).Where(s => s.Sport.SportName == id).Where(c => c.CourtName.Contains(terenCautat)).ToList();
                if (courts.Count==0)
                {
                    ModelState.AddModelError(string.Empty, "Ne pare rau, nu am gasit nici un teren!");
                }
                return View(courts);
            }
        }

        public ActionResult NotAllowed()
        {
            return View();
        }

        public ActionResult DespreNoi()
        {
            return View();
        }

        public ActionResult TermeniSiConditii()
        {
            return View();
        }

        public ActionResult ContactUs()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ContactUs(string your_name,string your_email,string your_enquiry)
        {

            if (your_email != null)
            {
                string subject = "Ati primit un mesaj de la " + your_name;
                string mesajBody = your_enquiry + ". Ma puteti contacta la adresa de email: " + your_email;
                Utilities.EmailSend("online.programare@gmail.com", subject, mesajBody);
                ViewBag.ContactSuccess = "Mesajul a fost trimis cu succes!";
            }
            return View("Index", db.Courts.Where(e => e.Hidden == false).ToList());
        }
    }
}

WhereToPlay/Views/Home/ContactUs.cshtml
@{ ViewBag.Title = "Contacteaza-ne"; }

<p>Pentru orice problema va rugam nu ezitati sa ne contactati!</p>

<form method="post" id="formulmeu">
    <div class="form_settings">
        <p id="namep"><span>Nume</span><input class="contact" type="text" name="your_name" value="" /></p>
        <p id="emailp"><span>Adresa de Email</span><input class="contact" type="text" name="your_email" value="" /></p>
        <p><span>Mesaj</span><textarea class="contact textarea" rows="8" cols="50" name="your_enquiry"></textarea></p>
        <p name="wordCount"><span>Cuvinte</span><input class="contact" type="text" name="your_wordCount" /></p>
        <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="ContactUs" value="Trimite"  id="trimitecontact"/></p>
    </div>
</form>
<script src="~/Scripts/jquery-2.2.0.js"></script>
<script src="~/Scripts/ValidateContactForm.js"></script>

WhereToPlay/Views/Home/DespreNoi.cshtml
@{ ViewBag.Title = "Despre Noi"; }

<p><b>Sunteți interesat să rezervați un teren de sport?</b> WhereToPlay.ro este un site care vă ajută să faceți rezervarea online gratuit și ușor, fără a fi necesară contactarea recepției. Sistem de rezervare online, WhereToPlay.ro răspunde nevoilor moderne de mobilitate și de optimizare a timpului oferit recreerii și exercițiilor fizice.</p>
<p>Doriți să aveți în față toate detaliile legate de ofertele existente? Toate datele necesare rezervării vă sunt acum centralizate și disponibile online. Astfel, decizia nu mai trebuie luată pe moment și în lipsa unor informații importante. WhereToPlay.ro vă oferă posibilitatea de a analiza comparativ facilitățile și tarifele terenurilor de sport care corespund căutărilor dumneavoastră. Puteți vizualiza alături de prieteni informațiile generale și intervalele orare disponibile în timp real, pentru a lua decizia potrivită.</p>
<p><b>Cum procedez?</b> Prin sistemul gratuit de rezervare online, clientul își creează un cont, se înregistrează și își rezervă terenul de sport selectat în intervalul ales printr-o simplă apăsare de buton. Clientul primește pe e-mail sau SMS confirmarea. La fel de accesibilă este și anularea unei rezervări.</p>
<p><b>Prezentare generala</b></p>
<p>Site-ul propune o prezentare complexă a unităților de sport (baze sportive, terenuri, săli de sport) existente în Cluj-Napoca, unde proprietarii de terenuri din Cluj-napova vor putea sa isi inscrie terenul,  oferind pentru fiecare în parte informații privind locația, tarifele practicate, condițiile oferite si nu numai.</p>
<p>Scopul WhereToPlay.ro este crearea unui sistem online eficient pentru persoanele care doresc să desfășoare activități sportive, facilitându-le rezervarea unităţilor de sport dorite, în funcție de locație, de perioadă și de intervalul de timp.</p>
<p>Viziunea WhereToPlay.ro este oferirea unui website informativ şi uşor de utilizat cu scopul de a pune la dispoziția sportivilor amatori sau profesioniști un mod util şi rentabil de a găsi şi rezerva dintr-o selecţie largă de opţiuni locația adecvată pentru a practica sportul dorit in Cluj-Napoca.</p>
<p><b><u>Beneficii pentru utilizatori:</u></b></p>
<p>
    <ul>
        <li>Rezervari la orice ora, 24 din 24 de ore</li>
        <li>Vizualizarea rapida a tuturor pozitiilor libere, avand astfel posibilitatea sa va rezervati unitatile de sport disponibile in locatia si perioada selectata</li>
        <li>Vizualizarea tuturor pozitiilor libere pentru unitățile de sport dintr-o anumită locație, pentru o programare</li>
        <li>Vizualizarea tarifelor, a starii terenului, promotiilor existente pentru anumite intervale orare</li>
        <li>Planificarea adecvată a tuturor programărilor, evităndu-se astfel suprapunerile</li>
        <li>Notificari prin email si SMS la fiecare rezervare noua</li>
    </ul>
</p>
<p><b><u>Beneficii pentru proprietarii de baze sportive:</u></b></p>
<p>
    <ul>
        <li>Reclama gratuita pentru terenurile de sport inscrise pe site</li>
        <li>Posibilitatea de a-si maximiza castigurile</li>
        <li>Sunt zile cand terenurile nu sunt rezervate in proportie de 100%... Nicio problema!</li>
        <li>Pe site sunt afisate pozitiile libere, care pot fi ocupate de persoanele care cauta un teren de sport</li>
        <li>Acces in orice moment la toate terenurile de sport inscrise pe site, direct pe telefonul mobil</li>
        <li>Planificarea adecvata a tuturor programarilor, evitandu-se astfel suprapunerile</li>
        <li>Notificari prin email la fiecare rezervare noua</li>
    </ul>
</p>

WhereToPlay/Views/Home/IndexBKP.cshtml
@model IEnumerable<WhereToPlay.Models.DB.Court>

<link href="~/Content/HomeIndex.css" rel="stylesheet" type="text/css" />

<div class="divTableRow">
    <ul class="nav navbar-nav">
        @{
            WhereToPlay.Models.WhereToPlayDb db = new WhereToPlay.Models.WhereToPlayDb();
            int spIDF = db.Sports.Where(s => s.SportName == "Fotbal").FirstOrDefault().IDSport;
            <li>
                <p>@Html.ActionLink("Fotbal", "IndexSports", new { id = spIDF })</p>
            </li>
        }

        @{
            int spIDT = db.Sports.Where(s => s.SportName == "Tenis").FirstOrDefault().IDSport;
            <li>
                <p>@Html.ActionLink("Tenis", "IndexSports", new { id = spIDT })</p>
            </li>
        }

        @{
            int spIDB = db.Sports.Where(s => s.SportName == "Baschet").FirstOrDefault().IDSport;
            <li>
                <p>@Html.ActionLink("Baschet", "IndexSports", new { id = spIDB })</p>
            </li>
        }
    </ul>
</div>

<div class="divTable">
    @for (int i = 0; i < Model.ToList().Count; i += 3)
    {
        <div class="divTableRow">
            @*coloana 1 *@
            <div class="divTableCell">
                <div class="divGol">
                    <p>@Model.ToList()[i].Sport.SportName / @Model.ToList()[i].CourtName</p>
                    @{
                        if (Model.ToList()[i].FileName1 != null)
                        {
                            string imageBase64 = Convert.ToBase64String(Model.ToList()[i].Content1);
                            string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                            <img src="@imageSrc" style="height:200px;width:300px;" />
                        }
                        else
                        {
                            if (Model.ToList()[i].FileName2 != null)
                            {
                                string imageBase64 = Convert.ToBase64String(Model.ToList()[i].Content2);
                                string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                <img src="@imageSrc" style="height:200px;width:300px;" />
                            }
                            else
                            {
                                if (Model.ToList()[i].FileName3 != null)
                                {
                                    string imageBase64 = Convert.ToBase64String(Model.ToList()[i].Content3);
                                    string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                    <img src="@imageSrc" style="height:200px;width:300px;" />
                                }
                                else
                                {
                                    <img src="~/Content/Images/no_image-500x500.png" style="height:200px;width:300px;" />
                                }
                            }
                        }
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <p>@Html.ActionLink("Inchiriaza", "Details", "Courts", new { id = Model.ToList()[i].IDCourt }, null)</p>
                    }
                    else
                    {
                        <p>@Html.ActionLink("Inchiriaza", "Login", "Account")</p>
                    }
                </div>
            </div>
            @if (i + 1 < Model.ToList().Count)
                {
                @*coloana 2 *@
                <div class="divTableCell">
                    <div class="divGol">
                        <p>@Model.ToList()[i + 1].Sport.SportName / @Model.ToList()[i + 1].CourtName</p>
                        @{
                            if (Model.ToList()[i + 1].FileName1 != null)
                            {
                                string imageBase64 = Convert.ToBase64String(Model.ToList()[i + 1].Content1);
                                string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                <img src="@imageSrc" style="height:200px;width:300px;" />
                            }
                            else
                            {
                                if (Model.ToList()[i + 1].FileName2 != null)
                                {
                                    string imageBase64 = Convert.ToBase64String(Model.ToList()[i + 1].Content2);
                                    string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                    <img src="@imageSrc" style="height:200px;width:300px;" />
                                }
                                else
                                {
                                    if (Model.ToList()[i + 1].FileName3 != null)
                                    {
                                        string imageBase64 = Convert.ToBase64String(Model.ToList()[i + 1].Content3);
                                        string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                        <img src="@imageSrc" style="height:200px;width:300px;" />
                                    }
                                    else
                                    {
                                        <img src="~/Content/Images/no_image-500x500.png" style="height:200px;width:300px;" />
                                    }
                                }
                            }
                        }
                        @if (Request.IsAuthenticated)
                    {
                            <p>@Html.ActionLink("Inchiriaza", "Details", "Courts", new { id = Model.ToList()[i + 1].IDCourt }, null)</p>
                        }
                        else
                        {
                            <p>@Html.ActionLink("Inchiriaza", "Login", "Account")</p>
                        }
                    </div>
                </div>
                            }
                            @*coloana 3 *@
                            @if (i + 2 < Model.ToList().Count)
                {
                                <div class="divTableCell">
                                    <div class="divGol">
                                        <p>@Model.ToList()[i + 2].Sport.SportName / @Model.ToList()[i + 2].CourtName</p>
                                        @{
                                            if (Model.ToList()[i + 2].FileName1 != null)
                                            {
                                                string imageBase64 = Convert.ToBase64String(Model.ToList()[i + 2].Content1);
                                                string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                                <img src="@imageSrc" style="height:200px;width:300px;" />
                                            }
                                            else
                                            {
                                                if (Model.ToList()[i + 2].FileName2 != null)
                                                {
                                                    string imageBase64 = Convert.ToBase64String(Model.ToList()[i + 2].Content2);
                                                    string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                                    <img src="@imageSrc" style="height:200px;width:300px;" />
                                                }
                                                else
                                                {
                                                    if (Model.ToList()[i + 2].FileName3 != null)
                                                    {
                                                        string imageBase64 = Convert.ToBase64String(Model.ToList()[i + 2].Content3);
                                                        string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                                        <img src="@imageSrc" style="height:200px;width:300px;" />
                                                    }
                                                    else
                                                    {
                                                        <img src="~/Content/Images/no_image-500x500.png" style="height:200px;width:300px;" />
                                                    }
                                                }
                                            }
                                        }
                                        @if (Request.IsAuthenticated)
                    {
                                            <p>@Html.ActionLink("Inchiriaza", "Details", "Courts", new { id = Model.ToList()[i + 2].IDCourt }, null)</p>
                                        }
                                        else
                                        {
                                            <p>@Html.ActionLink("Inchiriaza", "Login", "Account")</p>
                                        }
                                    </div>
                                </div>
                                            }
                        </div>
                                                //Aici e index-ul din Home
                                            }

</div>

WhereToPlay/Views/Home/NotAllowed.cshtml
@{ViewBag.Title = "Nepermis";}

<h2>NotAllowed</h2>

WhereToPlay/Views/Home/_IndexSport.cshtml
@model IEnumerable<WhereToPlay.Models.DB.Court>


    @foreach (WhereToPlay.Models.DB.Court item in Model)
    {
        @*<div class="divTableRow">
            <div class="divTableCell">*@
                <div class="divGol">
                    <p>@item.Sport.SportName / @item.CourtName</p>
                    @{
                        if (item.FileName1 != null)
                        {
                            string imageBase64 = Convert.ToBase64String(item.Content1);
                            string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                            if (Request.IsAuthenticated)
                            {
                            <a href='@Url.Action("Details", "Courts", new { id = item.IDCourt })'>
                                <img src="@imageSrc" style="height:200px;width:300px;" />
                            </a>
                            }
                            else
                            {
                                <img src="@imageSrc" style="height:200px;width:300px;" />
                            }
                        }
                        else
                        {
                            if (item.FileName2 != null)
                            {
                                string imageBase64 = Convert.ToBase64String(item.Content2);
                                string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                if (Request.IsAuthenticated)
                                {
                                    <a href='@Url.Action("Details", "Courts", new { id = item.IDCourt })'>
                                        <img src="@imageSrc" style="height:200px;width:300px;" />
                                    </a>
                                    }
                                    else
                                    {
                                    <img src="@imageSrc" style="height:200px;width:300px;" />
                                    }
                                }
                                else
                                {
                                    if (item.FileName3 != null)
                                    {
                                        string imageBase64 = Convert.ToBase64String(item.Content3);
                                        string imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                                        if (Request.IsAuthenticated)
                                        {
                                        <a href='@Url.Action("Details", "Courts", new { id = item.IDCourt })'>
                                            <img src="@imageSrc" style="height:200px;width:300px;" />
                                        </a>
                                        }
                                        else
                                        {
                                            <img src="@imageSrc" style="height:200px;width:300px;" />
                                    }
                                }
                                else
                                {
                                    if (item.Sport.SportName == "Fotbal")
                                    {
                                        <img src="~/Content/Images/fotbal.png" style="height:200px;width:300px;" />
                                    }
                                    else
                                    {
                                        if (item.Sport.SportName == "Tenis")
                                        {
                                            <img src="~/Content/Images/tenis.png" style="height:200px;width:300px;" />
                                        }
                                        else
                                        {
                                            if (item.Sport.SportName == "Baschet")
                                            {
                                                <img src="~/Content/Images/baschet.png" style="height:200px;width:300px;" />
                                            }
                                            else
                                            {
                                                <img src="~/Content/Images/no_image-500x500.png" style="height:200px;width:300px;" />
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <p>@Html.ActionLink("Inchiriaza", "Details", "Courts", new { id = item.IDCourt }, null)</p>
                    }
                    else
                    {
                        <p>@Html.ActionLink("Inchiriaza", "Login", "Account")</p>
                    }
                </div>
            @*</div>
        </div>*@
                        }
       

 